version: 2.1

workflows:
  version: 2.1
  build:
    jobs:
      - convert
      - build:
          requires:
            - convert
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main

jobs:
  convert:
    working_directory: ~/quickstart
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - run: 
          name: Install packages
          command: |
            git submodule sync
            git submodule update --init --recursive 
            pip install jupyter
            pip install nb2hugo
            touch logs.txt
            python convert-to-md.py -d
      - persist_to_workspace:
          root: .
          paths: content
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run:
          name: "build"
          command: hugo
      - persist_to_workspace:
          root: .
          paths: public
  deploy:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
           - "5b:ab:83:61:5b:c1:f5:8e:d0:89:33:ad:0b:0d:e8:ce"
      - checkout
      - run:
           name: Deploy Over SSH
           command: |
             ssh $SSH_USER@$SSH_HOST "python -m http.server 8000"
