version: 2.1

workflows:
  version: 2.1
  build:
    jobs:
      - convert
      - build:
          requires:
            - convert
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main

jobs:
  convert:
    working_directory: ~/quickstart
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - run: 
          name: Install packages
          command: |
            git submodule sync
            git submodule update --init --recursive 
            pip install jupyter
            pip install nb2hugo
            touch logs.txt
            python convert-to-md.py -d
      - persist_to_workspace:
          root: .
          paths: content
  build:
    working_directory: ~/quickstart
    docker:
      - image: z0li/hugo-builder:latest
    steps:
      - add_ssh_keys:
          fingerprints:
           - "5b:ab:83:61:5b:c1:f5:8e:d0:89:33:ad:0b:0d:e8:ce"
      - checkout
      - run: git submodule update --init
      - run: hugo -v -s /quickstart -d /quickstart/public
      - run:
          name: "test the generated html files"
          command: htmlproofer /src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
  deploy:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
           - "5b:ab:83:61:5b:c1:f5:8e:d0:89:33:ad:0b:0d:e8:ce"
      - checkout
      - run:
           name: push to master branch
           command: sh deploy.sh
