version: 2

workflows:
  version: 2
  build:
    jobs:
      - convert
      - build:
          requires:
            - convert
          filters:
            branches:
              only: main

jobs:
  convert:
    docker:
      - image: jupyter/datascience-notebook
      - command: docker run -p 8888:8888 -v ~/quickstart:/home/jovyan/quickstart jupyter/datascience-notebook
    working_directory: ~/quickstart
    steps:
      - run: 
          command: |
            %pwd
            pip install jupyter
            pip install nb2hugo
            touch logs.txt
            python convert-to-md.py -d
      - persist_to_workspace:
          root: content
          paths: .
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/content
    environment:
      HUGO_BUILD_DIR: public
    steps:
      - run: apk update && apk add git
      - checkout
      - run: HUGO_ENV=production hugo -F -v -d $HUGO_BUILD_DIR
      - persist_to_workspace:
          root: public
          paths: .
