version: 2.1

orbs:
  hugo: circleci/hugo@1.2.2

workflows:
  main:
    jobs:
      - convert
      - hugo/build:
          asciidoc: true
          html-proofer: true
          version: 0.80.0
          requires:
            - convert
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - hugo/build
          filters:
            branches:
              only: main

jobs:
  convert:
    working_directory: ~/quickstart
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - run: 
          name: Install packages
          command: |
            git submodule sync
            git submodule update --init --recursive 
            pip install jupyter
            pip install nb2hugo
            touch logs.txt
            python convert-to-md.py -d
      - persist_to_workspace:
          root: .
          paths: content
  deploy:
    docker:
      - image: cimg/base
    steps:
      - attach_workspace:
          at: my-site
      - run: ls -lah my-site
