version: 2

workflows:
  version: 2
  build:
    jobs:
      - convert
      - build:
          requires:
            - convert
          filters:
            branches:
              only: main

jobs:
  convert:
    docker:
      - image: circleci/python:3.7.6
    working_directory: ~/project/quickstart
    steps:
      - checkout:
          path: ~/project
      - run: 
          name: Install poetry packages
          command: |
            pwd
            ls -l
            pip install jupyter
            pip install nb2hugo
            touch logs.txt
            python convert-to-md.py -d
      - persist_to_workspace:
          root: content
          paths: .
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/content
    environment:
      HUGO_BUILD_DIR: public
    steps:
      - run: apk update && apk add git
      - checkout
      - run: HUGO_ENV=production hugo -F -v -d $HUGO_BUILD_DIR
      - persist_to_workspace:
          root: public
          paths: .
